// Locative case (miejscownik) for top Polish cities — "w {locative}"
// Polish declension is irregular, so this must be a curated mapping.
// Cities not in this map fall back to nominative title format.
export const CITY_LOCATIVE: Record<string, string> = {
  "warszawa": "Warszawie",
  "krakow": "Krakowie",
  "lodz": "Łodzi",
  "wroclaw": "Wrocławiu",
  "poznan": "Poznaniu",
  "gdansk": "Gdańsku",
  "szczecin": "Szczecinie",
  "bydgoszcz": "Bydgoszczy",
  "lublin": "Lublinie",
  "bialystok": "Białymstoku",
  "katowice": "Katowicach",
  "gdynia": "Gdyni",
  "czestochowa": "Częstochowie",
  "radom": "Radomiu",
  "sosnowiec": "Sosnowcu",
  "torun": "Toruniu",
  "kielce": "Kielcach",
  "rzeszow": "Rzeszowie",
  "gliwice": "Gliwicach",
  "olsztyn": "Olsztynie",
  "bielsko-biala": "Bielsku-Białej",
  "zabrze": "Zabrzu",
  "bytom": "Bytomiu",
  "ruda-slaska": "Rudzie Śląskiej",
  "tychy": "Tychach",
  "plock": "Płocku",
  "opole": "Opolu",
  "elblag": "Elblągu",
  "gorzow-wielkopolski": "Gorzowie Wielkopolskim",
  "walbrzych": "Wałbrzychu",
  "wloclawek": "Włocławku",
  "tarnow": "Tarnowie",
  "chorzow": "Chorzowie",
  "koszalin": "Koszalinie",
  "kalisz": "Kaliszu",
  "legnica": "Legnicy",
  "grudziadz": "Grudziądzu",
  "slupsk": "Słupsku",
  "jaworzno": "Jaworznie",
  "jastrzebie-zdroj": "Jastrzębiu-Zdroju",
  "nowy-sacz": "Nowym Sączu",
  "jelenia-gora": "Jeleniej Górze",
  "siedlce": "Siedlcach",
  "myslowice": "Mysłowicach",
  "pila": "Pile",
  "ostrow-wielkopolski": "Ostrowie Wielkopolskim",
  "konin": "Koninie",
  "inowroclaw": "Inowrocławiu",
  "lubin": "Lubinie",
  "suwalki": "Suwałkach",
  "zielona-gora": "Zielonej Górze",
  "tarnowskie-gory": "Tarnowskich Górach",
  "dabrowa-gornicza": "Dąbrowie Górniczej",
  "piotrkow-trybunalski": "Piotrkowie Trybunalskim",
  "zory": "Żorach",
  "pruszkow": "Pruszkowie",
  "lomza": "Łomży",
  "zamosc": "Zamościu",
  "ostrowiec-swietokrzyski": "Ostrowcu Świętokrzyskim",
  "wodzislaw-slaski": "Wodzisławiu Śląskim",
  "gniezno": "Gnieźnie",
  "stargard": "Stargardzie",
  "leszno": "Lesznie",
  "kedzierzyn-kozle": "Kędzierzynie-Koźlu",
  "chelm": "Chełmie",
  "przemysl": "Przemyślu",
  "nowy-targ": "Nowym Targu",
  "sanok": "Sanoku",
  "mielec": "Mielcu",
  "tczew": "Tczewie",
  "sieradz": "Sieradzu",
  "skierniewice": "Skierniewicach",
  "pabianice": "Pabianicach",
  "zgierz": "Zgierzu",
  "belchatow": "Bełchatowie",
  "tomaszow-mazowiecki": "Tomaszowie Mazowieckim",
  "wolomin": "Wołominie",
  "minsk-mazowiecki": "Mińsku Mazowieckim",
  "otwock": "Otwocku",
  "legionowo": "Legionowie",
  "nowy-dwor-mazowiecki": "Nowym Dworze Mazowieckim",
  "piaseczno": "Piasecznie",
  "grodzisk-mazowiecki": "Grodzisku Mazowieckim",
  // Kujawsko-Pomorskie
  "brodnica": "Brodnicy",
  "swiecie": "Świeciu",
  "chelmno": "Chełmnie",
  "naklo-nad-notecia": "Nakle nad Notecią",
  "aleksandrow-kujawski": "Aleksandrowie Kujawskim",
  "ciechocinek": "Ciechocinku",
  "rypin": "Rypinie",
  "lipno": "Lipnie",
  // Lubelskie
  "biala-podlaska": "Białej Podlaskiej",
  "pulawy": "Puławach",
  "krasnik": "Kraśniku",
  "hrubieszow": "Hrubieszowie",
  "lubartow": "Lubartowie",
  "swidnik": "Świdniku",
  "krasnystaw": "Krasnymstawie",
  "tomaszow-lubelski": "Tomaszowie Lubelskim",
  // Lubuskie
  "nowa-sol": "Nowej Soli",
  "zary": "Żarach",
  "zagan": "Żaganiu",
  "lubsko": "Lubsku",
  "gubin": "Gubinie",
  // Łódzkie
  "kutno": "Kutnie",
  "lowicz": "Łowiczu",
  "rawa-mazowiecka": "Rawie Mazowieckiej",
  "opoczno": "Opocznie",
  "radomsko": "Radomsku",
  "wielun": "Wieluniu",
  // Małopolskie
  "wieliczka": "Wieliczce",
  "oswiecim": "Oświęcimiu",
  "wadowice": "Wadowicach",
  "gorlice": "Gorlicach",
  "limanowa": "Limanowej",
  "zakopane": "Zakopanem",
  "chrzanow": "Chrzanowie",
  "olkusz": "Olkuszu",
  "myslenice": "Myślenicach",
  "skawina": "Skawinie",
  "bochnia": "Bochni",
  "sucha-beskidzka": "Suchej Beskidzkiej",
  "andrychow": "Andrychowie",
  "miechow": "Miechowie",
  "trzebinia": "Trzebini",
  "kety": "Kętach",
  // Mazowieckie
  "ciechanow": "Ciechanowie",
  "ostroleka": "Ostrołęce",
  "zyrardow": "Żyrardowie",
  "garwolin": "Garwolinie",
  "wyszkow": "Wyszkowie",
  "grojec": "Grójcu",
  "ozarow-mazowiecki": "Ożarowie Mazowieckim",
  "ostrow-mazowiecka": "Ostrowi Mazowieckiej",
  "pultusk": "Pułtusku",
  "przasnysz": "Przasnyszu",
  "makow-mazowiecki": "Makowie Mazowieckim",
  "kozienice": "Kozienicach",
  "pionki": "Pionkach",
  // Opolskie
  "nysa": "Nysie",
  "brzeg": "Brzegu",
  "kluczbork": "Kluczborku",
  "prudnik": "Prudniku",
  "strzelce-opolskie": "Strzelcach Opolskich",
  "namyslow": "Namysłowie",
  "glucholazy": "Głuchołazach",
  // Podkarpackie
  "stalowa-wola": "Stalowej Woli",
  "debica": "Dębicy",
  "jaslo": "Jaśle",
  "krosno": "Krośnie",
  "tarnobrzeg": "Tarnobrzegu",
  "nisko": "Nisku",
  "brzozow": "Brzozowie",
  "lesko": "Lesku",
  // Podlaskie
  "bielsk-podlaski": "Bielsku Podlaskim",
  "hajnowka": "Hajnówce",
  "zambrow": "Zambrowie",
  "siemiatycze": "Siemiatyczach",
  "augustow": "Augustowie",
  "mragowo": "Mrągowie",
  // Pomorskie
  "kwidzyn": "Kwidzynie",
  "malbork": "Malborku",
  "wejherowo": "Wejherowie",
  "lebork": "Lęborku",
  "bytow": "Bytowie",
  "starogard-gdanski": "Starogardzie Gdańskim",
  "chojnice": "Chojnicach",
  "czluchow": "Człuchowie",
  "nowy-dwor-gdanski": "Nowym Dworze Gdańskim",
  "puck": "Pucku",
  // Śląskie
  "rybnik": "Rybniku",
  "zawiercie": "Zawierciu",
  "bedzin": "Będzinie",
  "siemianowice-slaskie": "Siemianowicach Śląskich",
  "mikolow": "Mikołowie",
  "pszczyna": "Pszczynie",
  "raciborz": "Raciborzu",
  "swietochlowice": "Świętochłowicach",
  "piekary-slaskie": "Piekarach Śląskich",
  "knurow": "Knurowie",
  "czechowice-dziedzice": "Czechowicach-Dziedzicach",
  "cieszyn": "Cieszynie",
  "zywiec": "Żywcu",
  "skoczow": "Skoczowie",
  // Świętokrzyskie
  "konskie": "Końskich",
  "busko-zdroj": "Busku-Zdroju",
  "skarzysko-kamienna": "Skarżysku-Kamiennej",
  "pinczow": "Pińczowie",
  "opatow": "Opatowie",
  "jedrzejow": "Jędrzejowie",
  "wloszczowa": "Włoszczowej",
  // Warmińsko-Mazurskie
  "ilawa": "Iławie",
  "szczytno": "Szczytnie",
  "ketrzyn": "Kętrzynie",
  "bartoszyce": "Bartoszycach",
  "braniewo": "Braniewie",
  "elk": "Ełku",
  "ostroda": "Ostródzie",
  "morag": "Morągu",
  "gizycko": "Giżycku",
  "lidzbark-warminski": "Lidzbarku Warmińskim",
  // Wielkopolskie
  "kolo": "Kole",
  "turek": "Turku",
  "rawicz": "Rawiczu",
  "kepno": "Kępnie",
  "gostyn": "Gostyniu",
  "wrzesnia": "Wrześni",
  "szamotuly": "Szamotułach",
  "sroda-wielkopolska": "Środzie Wielkopolskiej",
  "pleszew": "Pleszewie",
  "zlotow": "Złotowie",
  "chodzierz": "Chodzieży",
  // Zachodniopomorskie
  "swinoujscie": "Świnoujściu",
  "szczecinek": "Szczecinku",
  "walcz": "Wałczu",
  "bialogard": "Białogardzie",
  "slawno": "Sławnie",
  "kolobrzeg": "Kołobrzegu",
  "drawsko-pomorskie": "Drawsku Pomorskim",
  "pyrzyce": "Pyrzycach",
};
