// Locative case (miejscownik) for top Polish cities — "w {locative}"
// Polish declension is irregular, so this must be a curated mapping.
// Cities not in this map fall back to nominative title format.
export const CITY_LOCATIVE: Record<string, string> = {
  "warszawa": "Warszawie",
  "krakow": "Krakowie",
  "lodz": "Łodzi",
  "wroclaw": "Wrocławiu",
  "poznan": "Poznaniu",
  "gdansk": "Gdańsku",
  "szczecin": "Szczecinie",
  "bydgoszcz": "Bydgoszczy",
  "lublin": "Lublinie",
  "bialystok": "Białymstoku",
  "katowice": "Katowicach",
  "gdynia": "Gdyni",
  "czestochowa": "Częstochowie",
  "radom": "Radomiu",
  "sosnowiec": "Sosnowcu",
  "torun": "Toruniu",
  "kielce": "Kielcach",
  "rzeszow": "Rzeszowie",
  "gliwice": "Gliwicach",
  "olsztyn": "Olsztynie",
  "bielsko-biala": "Bielsku-Białej",
  "zabrze": "Zabrzu",
  "bytom": "Bytomiu",
  "ruda-slaska": "Rudzie Śląskiej",
  "tychy": "Tychach",
  "plock": "Płocku",
  "opole": "Opolu",
  "elblag": "Elblągu",
  "gorzow-wielkopolski": "Gorzowie Wielkopolskim",
  "walbrzych": "Wałbrzychu",
  "wloclawek": "Włocławku",
  "tarnow": "Tarnowie",
  "chorzow": "Chorzowie",
  "koszalin": "Koszalinie",
  "kalisz": "Kaliszu",
  "legnica": "Legnicy",
  "grudziadz": "Grudziądzu",
  "slupsk": "Słupsku",
  "jaworzno": "Jaworznie",
  "jastrzebie-zdroj": "Jastrzębiu-Zdroju",
  "nowy-sacz": "Nowym Sączu",
  "jelenia-gora": "Jeleniej Górze",
  "siedlce": "Siedlcach",
  "myslowice": "Mysłowicach",
  "pila": "Pile",
  "ostrow-wielkopolski": "Ostrowie Wielkopolskim",
  "konin": "Koninie",
  "inowroclaw": "Inowrocławiu",
  "lubin": "Lubinie",
  "suwalki": "Suwałkach",
  "zielona-gora": "Zielonej Górze",
  "tarnowskie-gory": "Tarnowskich Górach",
  "dabrowa-gornicza": "Dąbrowie Górniczej",
  "piotrkow-trybunalski": "Piotrkowie Trybunalskim",
  "zory": "Żorach",
  "pruszkow": "Pruszkowie",
  "lomza": "Łomży",
  "zamosc": "Zamościu",
  "ostrowiec-swietokrzyski": "Ostrowcu Świętokrzyskim",
  "wodzislaw-slaski": "Wodzisławiu Śląskim",
  "gniezno": "Gnieźnie",
  "stargard": "Stargardzie",
  "leszno": "Lesznie",
  "kedzierzyn-kozle": "Kędzierzynie-Koźlu",
  "chelm": "Chełmie",
  "przemysl": "Przemyślu",
  "nowy-targ": "Nowym Targu",
  "sanok": "Sanoku",
  "mielec": "Mielcu",
  "tczew": "Tczewie",
  "sieradz": "Sieradzu",
  "skierniewice": "Skierniewicach",
  "pabianice": "Pabianicach",
  "zgierz": "Zgierzu",
  "belchatow": "Bełchatowie",
  "tomaszow-mazowiecki": "Tomaszowie Mazowieckim",
  "wolomin": "Wołominie",
  "minsk-mazowiecki": "Mińsku Mazowieckim",
  "otwock": "Otwocku",
  "legionowo": "Legionowie",
  "nowy-dwor-mazowiecki": "Nowym Dworze Mazowieckim",
  "piaseczno": "Piasecznie",
  "grodzisk-mazowiecki": "Grodzisku Mazowieckim",
};
